image: golang

variables:
  REPO_NAME: gitlab.com/$CI_PROJECT_PATH

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - style
  - test
  - release

markdown:
  stage: style
  image: ruby
  script:
    - gem install mdl
    - mdl .

spelling:
  stage: style
  script:
    - go get -u github.com/client9/misspell/cmd/misspell
    - misspell -error .

go-build:
  stage: test
  script:
    - go get ./...
    - go build

go-test:
  stage: test
  script:
    - go get -t ./...
    - go test -v ./...

golangci-lint:
  stage: test
  script:
    - go get -t ./...
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh
      | bash -s v1.8.1
    - ./bin/golangci-lint run --enable-all ./...

docker-build:
  stage: release
  image: docker:git
  variables:
    IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH
  services:
    - docker:dind
  script:
    - docker info
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $IMAGE_NAME:latest
    - docker tag $IMAGE_NAME $IMAGE_NAME:$(git describe --always --tags)
    - docker push $IMAGE_NAME
  only:
    - tags
    - master
